### ISSUE TITLE
local variable 'msrc' referenced before assignment

### ISSUE THREAD

**Issue by RocaVincent** [bigting84/style_transfer_harmonization#2]
When running the script *harmonize_images.sh*, the following error appears for each image: 
```
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 73, in main
    solver.sample(loaders)
  File "/anaconda3/envs/style_harmonization/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/style_transfer_harmonization/core/solver.py", line 185, in sample
    utils.translate_using_reference_2(nets_ema, args, src.x, ref.x, ref.y, fname)
  File "/anaconda3/envs/style_harmonization/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/style_transfer_harmonization/core/utils.py", line 170, in translate_using_reference_2
    del x_concat, x_concat2, x_concat_np, msrc#, mdic
UnboundLocalError: local variable 'msrc' referenced before assignment
```

**Comment by vakharia-aarya** [comment]
Thank you for pointing it out, however the program should still execute correctly. 
We have resolved the issue in the most recent commit.
